import type { TopicSource } from "./topicContract";

export const learningVideos: Record<string, TopicSource[]> = {
  "human-ai-responsibility": [
    {
      title: "Why AI Agents Need A Human in the Loop Now",
      url: "https://www.youtube.com/watch?v=cmEJ-5zYKHA",
      type: "learning-video",
      mediaType: "video",
      duration: "7:27",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Was ist Vertrauenswürdige KI?",
      url: "https://www.youtube.com/watch?v=sNHZjpXlZl8",
      type: "learning-video",
      mediaType: "video",
      duration: "19:43",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "What is AI Ethics?",
      url: "https://www.youtube.com/watch?v=aGwYtUzMQUk",
      type: "learning-video",
      mediaType: "video",
      duration: "6:10",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "How to implement AI Ethics",
      url: "https://www.youtube.com/watch?v=muLPOvIEtaw",
      type: "learning-video",
      mediaType: "video",
      duration: "3:44",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "problem-understanding-and-change-boundaries": [
    {
      title: "Akzeptanzkriterien richtig formulieren – mit Beispielen",
      url: "https://www.youtube.com/watch?v=VNCwMVAo2tg",
      type: "learning-video",
      mediaType: "video",
      duration: "6:49",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "User Stories and Acceptance Criteria EXAMPLE (Agile Story Tutorial)",
      url: "https://www.youtube.com/watch?v=q26147zlcMU",
      type: "learning-video",
      mediaType: "video",
      duration: "11:56",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "User Story Mapping 101",
      url: "https://www.youtube.com/watch?v=TaMLUf3gISo",
      type: "learning-video",
      mediaType: "video",
      duration: "3:05",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Requirement Specification vs User Stories",
      url: "https://www.youtube.com/watch?v=KP0U3I-f9-Y",
      type: "learning-video",
      mediaType: "video",
      duration: "17:34",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "domain-language-and-complexity": [
    {
      title:
        "Subdomains vs Bounded-Contexts in Domain-Driven Design (DDD) // deutsch",
      url: "https://www.youtube.com/watch?v=yQgCmMBNle4",
      type: "learning-video",
      mediaType: "video",
      duration: "10:14",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "So gelingt DDD // deutsch",
      url: "https://www.youtube.com/watch?v=Z0FWfVsRheE",
      type: "learning-video",
      mediaType: "video",
      duration: "8:02",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Domain-Driven Design: Bounded Contexts Explained! 🚀",
      url: "https://www.youtube.com/watch?v=8SPVfacnFvM",
      type: "learning-video",
      mediaType: "video",
      duration: "14:01",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Unlocking Bounded Contexts in Domain-Driven Design – A Practical Guide",
      url: "https://www.youtube.com/watch?v=kLLsVT_53bw",
      type: "learning-video",
      mediaType: "video",
      duration: "21:34",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "project-documentation-and-checklists": [
    {
      title: "Tipps für die technische Dokumentation // deutsch",
      url: "https://www.youtube.com/watch?v=BNBDkIJxDm0",
      type: "learning-video",
      mediaType: "video",
      duration: "13:59",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Definition of Done // deutsch",
      url: "https://www.youtube.com/watch?v=Lgi2d2ft7ok",
      type: "learning-video",
      mediaType: "video",
      duration: "6:29",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "What nobody tells you about documentation",
      url: "https://www.youtube.com/watch?v=t4vKPhjcMZg",
      type: "learning-video",
      mediaType: "video",
      duration: "30:52",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Better docs, happier users: What we learned applying Diataxis to HoloViz libraries",
      url: "https://www.youtube.com/watch?v=buEKMi4tAew",
      type: "learning-video",
      mediaType: "video",
      duration: "29:57",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "open-knowledge-format": [
    {
      title: "Warum jede KI dein Unternehmen neu erfindet - und was OKF ändert",
      url: "https://www.youtube.com/watch?v=_LZJ-OiPzV0",
      type: "learning-video",
      mediaType: "video",
      duration: "4:31",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Google's Open Knowledge Format: Just Markdown for AI Agents",
      url: "https://www.youtube.com/watch?v=14C0E6pwBIQ",
      type: "learning-video",
      mediaType: "video",
      duration: "6:53",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Open Knowledge Format Explained | Google's New AI Standard",
      url: "https://www.youtube.com/watch?v=wczuwg9EZdg",
      type: "learning-video",
      mediaType: "video",
      duration: "8:38",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Open Knowledge Format (OKF): The Missing Layer for AI Agents",
      url: "https://www.youtube.com/watch?v=5zUK_UB5HtY",
      type: "learning-video",
      mediaType: "video",
      duration: "24:27",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "goal-discovery-and-stop-criteria": [
    {
      title: "Tutorial: Projektmanagement - Projektziele",
      url: "https://www.youtube.com/watch?v=MvRbBamMZm0",
      type: "learning-video",
      mediaType: "video",
      duration: "8:55",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "User Stories and Acceptance Criteria EXAMPLE (Agile Story Tutorial)",
      url: "https://www.youtube.com/watch?v=q26147zlcMU",
      type: "learning-video",
      mediaType: "video",
      duration: "11:56",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "User Story Mapping 101",
      url: "https://www.youtube.com/watch?v=TaMLUf3gISo",
      type: "learning-video",
      mediaType: "video",
      duration: "3:05",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "User Story Mapping Tutorial: How to Create and Use Story Maps",
      url: "https://www.youtube.com/watch?v=uj3PlPDAlHU",
      type: "learning-video",
      mediaType: "video",
      duration: "11:38",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "agents-md": [
    {
      title: "CLAUDE.md & AGENTS.md - besserer Code und weniger Tokens",
      url: "https://www.youtube.com/watch?v=U7gu7vT0ib0",
      type: "learning-video",
      mediaType: "video",
      duration: "9:15",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "OpenAI Codex Tutorial #6 - Using the AGENTS.md file",
      url: "https://www.youtube.com/watch?v=NlNuoH5PPl4",
      type: "learning-video",
      mediaType: "video",
      duration: "4:44",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "How I Write My AGENTS.md Files  - Best Practices",
      url: "https://www.youtube.com/watch?v=6w88NVf2_lY",
      type: "learning-video",
      mediaType: "video",
      duration: "14:46",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Improve your AI code output with AGENTS.md (+ my best tips)",
      url: "https://www.youtube.com/watch?v=KEK_WcSTiuE",
      type: "learning-video",
      mediaType: "video",
      duration: "7:00",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "ears-requirements": [
    {
      title: "Easy Approach to Requirements Syntax (EARS) - The Basics",
      url: "https://www.youtube.com/watch?v=pa8C449yhCg",
      type: "learning-video",
      mediaType: "video",
      duration: "13:33",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "L07 10 Requirements Templates (EARS)",
      url: "https://www.youtube.com/watch?v=CT1FkZyceQY",
      type: "learning-video",
      mediaType: "video",
      duration: "2:44",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Easy Approach to Requirements Syntax (EARS) -  Using EARS in requirements documents",
      url: "https://www.youtube.com/watch?v=Fey75aFEm7w",
      type: "learning-video",
      mediaType: "video",
      duration: "10:55",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "design-and-legacy-specification": [
    {
      title: "Legacy Code angstfrei mit der Golden Master Technik ändern",
      url: "https://www.youtube.com/watch?v=3wPZGfSiWYw",
      type: "learning-video",
      mediaType: "video",
      duration: "31:03",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "How to test legacy code with characterization tests (JavaScript)",
      url: "https://www.youtube.com/watch?v=2q5PdGdlL8Y",
      type: "learning-video",
      mediaType: "video",
      duration: "11:31",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Working Effectively with Legacy Code • Michael Feathers & Christian Clausen • GOTO 2023",
      url: "https://www.youtube.com/watch?v=P_6eDL1aqtA&t=411s",
      type: "learning-video",
      mediaType: "video",
      duration: "45:42",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
      learningSegment: {
        start: "06:51",
        end: "45:02",
      },
    },
    {
      title: "Working Effectively with Legacy Code with Michael Feathers",
      url: "https://www.youtube.com/watch?v=UiU6khrBuV8",
      type: "learning-video",
      mediaType: "video",
      duration: "23:40",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "standards-and-constraint-rationale": [
    {
      title:
        "OWASP Application Security Verification Standard (ASVS) - Shanni Prutchi, Ryan Armstrong",
      url: "https://www.youtube.com/watch?v=BnP2vls88fw",
      type: "learning-video",
      mediaType: "video",
      duration: "35:17",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "What's New in ASVS V5 - Eden Yardeni - NDC Security 2026",
      url: "https://www.youtube.com/watch?v=SHSpUsVmDLA",
      type: "learning-video",
      mediaType: "video",
      duration: "45:29",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "OWASP Spotlight - Project 19 - OWASP Application Security Verification standard (ASVS)",
      url: "https://www.youtube.com/watch?v=3puIavsZfAk",
      type: "learning-video",
      mediaType: "video",
      duration: "10:12",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "llm-fallibility-and-counterchecks": [
    {
      title:
        "Lügt ChatGPT? 4 Wege, um KI-Fehler zu vermeiden & Tools für genauere Ergebnisse | Kurz erklärt",
      url: "https://www.youtube.com/watch?v=-ttJuqi8Rho",
      type: "learning-video",
      mediaType: "video",
      duration: "5:21",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Why Large Language Models Hallucinate",
      url: "https://www.youtube.com/watch?v=cfqtFvWOfg0",
      type: "learning-video",
      mediaType: "video",
      duration: "9:37",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Understanding AI Agent Hallucination in AI Systems",
      url: "https://www.youtube.com/watch?v=bNRhppHct54",
      type: "learning-video",
      mediaType: "video",
      duration: "10:51",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Why do AI models hallucinate?",
      url: "https://www.youtube.com/watch?v=005JLRt3gXI",
      type: "learning-video",
      mediaType: "video",
      duration: "5:13",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "context-selection-and-reset": [
    {
      title: "Effektives Context Engineering für KI Agenten",
      url: "https://www.youtube.com/watch?v=dPhyDkU-0zA",
      type: "learning-video",
      mediaType: "video",
      duration: "10:29",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "What Is Context Engineering? Why It Matters for AI Agents",
      url: "https://www.youtube.com/watch?v=Qx0fCqpkBus",
      type: "learning-video",
      mediaType: "video",
      duration: "9:56",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Context Engineering vs. Prompt Engineering: Smarter AI with RAG & Agents",
      url: "https://www.youtube.com/watch?v=vD0E3EUb8-8",
      type: "learning-video",
      mediaType: "video",
      duration: "7:52",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Warum dein Claude Code Agent wichtigen Kontext vergisst (und wie du es behebst)",
      url: "https://www.youtube.com/watch?v=Po3oo1foAVQ",
      type: "learning-video",
      mediaType: "video",
      duration: "23:12",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
  ],
  "coding-agent-context-and-trust-boundaries": [
    {
      title: "Die größte Sicherheitslücke der KI: Prompt Injection erklärt",
      url: "https://www.youtube.com/watch?v=sPQfn_nGr30",
      type: "learning-video",
      mediaType: "video",
      duration: "14:07",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Securing AI Agents: How to Prevent Hidden Prompt Injection Attacks",
      url: "https://www.youtube.com/watch?v=5ZA1lTxTH3c",
      type: "learning-video",
      mediaType: "video",
      duration: "10:07",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "What Is a Prompt Injection Attack?",
      url: "https://www.youtube.com/watch?v=jrHRe9lSqqA",
      type: "learning-video",
      mediaType: "video",
      duration: "10:57",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "What is Agentic Security Runtime? Securing AI Agents",
      url: "https://www.youtube.com/watch?v=NH0plIdqDMk",
      type: "learning-video",
      mediaType: "video",
      duration: "4:59",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "codebase-memory-for-large-repos": [
    {
      title:
        "Codebase Memory MCP GitHub Setup Guide: Index Repos Locally and Trace Breakages Faster",
      url: "https://www.youtube.com/watch?v=3GuP8gdE2Fk",
      type: "learning-video",
      mediaType: "video",
      duration: "4:28",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Codebase-Memory-MCP: The Tool I Missed in My Code Knowledge Graph Comparison (120x Fewer Tokens)",
      url: "https://www.youtube.com/watch?v=5kAJ7CA7ZB4",
      type: "learning-video",
      mediaType: "video",
      duration: "11:17",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Graphify vs CodeGraph: I Tested Both With Claude Code",
      url: "https://www.youtube.com/watch?v=Xr2MjfirjqA",
      type: "learning-video",
      mediaType: "video",
      duration: "9:35",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "token-efficiency-tools": [
    {
      title: "RTK: Token Killer for AI Agents – Real Savings or Hidden Costs?",
      url: "https://www.youtube.com/watch?v=3BHcuLZhZgM",
      type: "learning-video",
      mediaType: "video",
      duration: "4:01",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "I Cut My Claude Code Token Costs by 80% With This Tool",
      url: "https://www.youtube.com/watch?v=_Fo9hfgTlMw",
      type: "learning-video",
      mediaType: "video",
      duration: "8:05",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "RTK or Headroom? Why I Changed My Claude Code Setup",
      url: "https://www.youtube.com/watch?v=fgIbgHMwtWg",
      type: "learning-video",
      mediaType: "video",
      duration: "10:54",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "protect-secrets-and-sensitive-data-with-ai": [
    {
      title: "Claude Code: So schützt du deine API-Keys (.env Setup)",
      url: "https://www.youtube.com/watch?v=yS0rEzcXfm4",
      type: "learning-video",
      mediaType: "video",
      duration: "9:31",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Secrets Management: Secure Credentials & Avoid Data Leaks",
      url: "https://www.youtube.com/watch?v=BqekRTA6VCs",
      type: "learning-video",
      mediaType: "video",
      duration: "9:40",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "AI Is Exposing Your Data: An AI Security Problem You Can't See",
      url: "https://www.youtube.com/watch?v=kyJ1vd7yEPc",
      type: "learning-video",
      mediaType: "video",
      duration: "11:29",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Protecting Data in AI: Strategies for Security & Governance",
      url: "https://www.youtube.com/watch?v=LyfG7SGRiZA",
      type: "learning-video",
      mediaType: "video",
      duration: "15:19",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "research-plan-tasks": [
    {
      title: "Claude Code Tutorial #05 | Plan Modus und Version 2 Update",
      url: "https://www.youtube.com/watch?v=JDX-ljnaW2A",
      type: "learning-video",
      mediaType: "video",
      duration: "14:45",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "The Explore → Plan → Code → Commit workflow in Claude Code",
      url: "https://www.youtube.com/watch?v=xJQuF02NAK8",
      type: "learning-video",
      mediaType: "video",
      duration: "3:11",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "I was an AI skeptic. Then I tried plan mode",
      url: "https://www.youtube.com/watch?v=WNx-s-RxVxk",
      type: "learning-video",
      mediaType: "video",
      duration: "12:20",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "How I use Claude Code for real engineering",
      url: "https://www.youtube.com/watch?v=kZ-zzHVUrO4",
      type: "learning-video",
      mediaType: "video",
      duration: "10:11",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "spec-driven-development-openspec": [
    {
      title:
        "Stop Vibe Coding: Spec-Driven Development with OpenSpec (in 8 minutes)",
      url: "https://www.youtube.com/watch?v=P4EwAIflyq8",
      type: "learning-video",
      mediaType: "video",
      duration: "7:55",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "OpenSpec on a Real Project: What the Demos Don’t Show",
      url: "https://www.youtube.com/watch?v=YHPMs252Opc",
      type: "learning-video",
      mediaType: "video",
      duration: "11:32",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Getting Started with OpenSpec | Spec Driven Development | Setup Tutorial",
      url: "https://www.youtube.com/watch?v=raPTOBUpc3M",
      type: "learning-video",
      mediaType: "video",
      duration: "5:47",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "coding-agent-interface-selection": [
    {
      title: "Claude Code VS. Codex VS. Cursor: Welche KI codet am BESTEN?",
      url: "https://www.youtube.com/watch?v=oQgAytGUXLc",
      type: "learning-video",
      mediaType: "video",
      duration: "22:48",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Claude Code vs GPT Codex: Ehrlicher Vergleich",
      url: "https://www.youtube.com/watch?v=ncNG21JfYws",
      type: "learning-video",
      mediaType: "video",
      duration: "7:02",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "A very subjective comparison of Claude Code, OpenCode, Cursor & GitHub Copilot",
      url: "https://www.youtube.com/watch?v=dMSZ0WcK1oI",
      type: "learning-video",
      mediaType: "video",
      duration: "18:30",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Das Geheimnis guter KI-Agents: Die Harness-Schicht erklärt",
      url: "https://www.youtube.com/watch?v=7_F2rGhK0iE",
      type: "learning-video",
      mediaType: "video",
      duration: "9:47",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
  ],
  "agent-skills-and-commands": [
    {
      title:
        "SKILL.md Tutorial: So gibst du deinem KI-Agenten echte Fähigkeiten",
      url: "https://www.youtube.com/watch?v=-qwEBmCo2f8",
      type: "learning-video",
      mediaType: "video",
      duration: "41:17",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Claude Agent Skills Explained",
      url: "https://www.youtube.com/watch?v=fOxC44g8vig",
      type: "learning-video",
      mediaType: "video",
      duration: "3:14",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "What AI Agent Skills Are and How They Work",
      url: "https://www.youtube.com/watch?v=Lg-meK5IU8Q",
      type: "learning-video",
      mediaType: "video",
      duration: "12:25",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "5 Best Practices for Building AI Agent Skills",
      url: "https://www.youtube.com/watch?v=qYNs80FKIVc",
      type: "learning-video",
      mediaType: "video",
      duration: "13:22",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "spec-framework-selection": [
    {
      title: "Was niemand über GitHub's Spec Kit sagt",
      url: "https://www.youtube.com/watch?v=fsVX9OfkFi0",
      type: "learning-video",
      mediaType: "video",
      duration: "13:25",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Spec-Driven Development mit Claude Code: Ein praxisorientierter Leitfaden",
      url: "https://www.youtube.com/watch?v=z6MWGIa-bos",
      type: "learning-video",
      mediaType: "video",
      duration: "8:56",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "OpenSpec on a Real Project: What the Demos Don’t Show",
      url: "https://www.youtube.com/watch?v=YHPMs252Opc",
      type: "learning-video",
      mediaType: "video",
      duration: "11:32",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "This “Anti-Vibe Coding” Tool Is Actually Brilliant",
      url: "https://www.youtube.com/watch?v=qQZENQkraT4",
      type: "learning-video",
      mediaType: "video",
      duration: "10:55",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "parallel-agent-task-boundaries": [
    {
      title: "Claude Code Agent Teams: Mehrere KI-Agents coden parallel",
      url: "https://www.youtube.com/watch?v=Ag6Ly61Mc3E",
      type: "learning-video",
      mediaType: "video",
      duration: "11:38",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Multi Agent Systems Explained: How AI Agents & LLMs Work Together",
      url: "https://www.youtube.com/watch?v=sWH0T4Zez6I",
      type: "learning-video",
      mediaType: "video",
      duration: "7:57",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Multi-agent workflows in VS Code",
      url: "https://www.youtube.com/watch?v=J5KTpq7hVn4",
      type: "learning-video",
      mediaType: "video",
      duration: "5:08",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Das Geheimnis guter KI-Agents: Die Harness-Schicht erklärt",
      url: "https://www.youtube.com/watch?v=7_F2rGhK0iE",
      type: "learning-video",
      mediaType: "video",
      duration: "9:47",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
  ],
  "git-worktrees-for-isolated-changes": [
    {
      title: "#147 Topic: Git Worktree für Parallele Coding Agenten",
      url: "https://www.youtube.com/watch?v=SxQZb51WJY0",
      type: "learning-video",
      mediaType: "video",
      duration: "24:30",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Git Worktrees Tutorial #1 - What are Git Worktrees?",
      url: "https://www.youtube.com/watch?v=Vf_0QpLsFRs",
      type: "learning-video",
      mediaType: "video",
      duration: "7:49",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Git Worktrees Tutorial #2 - Adding Git Worktrees",
      url: "https://www.youtube.com/watch?v=5RB7RJ-d7Zk",
      type: "learning-video",
      mediaType: "video",
      duration: "7:03",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Git Worktrees Tutorial #5 - Worktrees in Agentic Coding Workflows",
      url: "https://www.youtube.com/watch?v=1QNrxuUu5CU",
      type: "learning-video",
      mediaType: "video",
      duration: "4:12",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "code-navigation-with-symbols-and-references": [
    {
      title:
        "IntelliJ IDEA schnell lernen: Die wichtigsten Funktionen für den Einstieg",
      url: "https://www.youtube.com/watch?v=CYcMMSHbz8w",
      type: "learning-video",
      mediaType: "video",
      duration: "39:31",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Navigation in IntelliJ IDEA",
      url: "https://www.youtube.com/watch?v=1UHsJyCq1SU",
      type: "learning-video",
      mediaType: "video",
      duration: "8:00",
      origin: "primary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Navigating your code in VS Code — Symbols, definitions, references, navigation, and more!",
      url: "https://www.youtube.com/watch?v=_4rSbklsVkk&t=935s",
      type: "learning-video",
      mediaType: "video",
      duration: "53:26",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
      learningSegment: {
        start: "15:35",
        end: "49:42",
      },
    },
    {
      title: "IntelliJ Navigation Shortcuts You Need to Know",
      url: "https://www.youtube.com/watch?v=bWivMas6Ilw",
      type: "learning-video",
      mediaType: "video",
      duration: "6:31",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "versioned-library-docs-with-context7": [
    {
      title: "Wie Du MCP-Server für Claude Code einrichtest (zu einfach)",
      url: "https://www.youtube.com/watch?v=9RiTjWRT8kA",
      type: "learning-video",
      mediaType: "video",
      duration: "4:35",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Make AI Use Live Documentation with Context7 MCP",
      url: "https://www.youtube.com/watch?v=Tk4y63IsA4s",
      type: "learning-video",
      mediaType: "video",
      duration: "6:17",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "How to use Context7 tutorial",
      url: "https://www.youtube.com/watch?v=IJipWGrElhE",
      type: "learning-video",
      mediaType: "video",
      duration: "5:49",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Context 7 MCP: Get Documentation Instantly + VS Code Setup",
      url: "https://www.youtube.com/watch?v=-ls0D-rtET4",
      type: "learning-video",
      mediaType: "video",
      duration: "4:21",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "specialized-subagents-and-ownership": [
    {
      title: "Claude Code Sub-Agents erklärt - Mit Claude ein Team bauen",
      url: "https://www.youtube.com/watch?v=8ex-HOTYOmM",
      type: "learning-video",
      mediaType: "video",
      duration: "17:51",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Alles, was du über Claude Code Subagents wissen musst (in unter 40min)",
      url: "https://www.youtube.com/watch?v=0g_ApRmfOjs",
      type: "learning-video",
      mediaType: "video",
      duration: "37:07",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Introduction to Sub Agents in GitHub Copilot | Multi-Agent Workflows",
      url: "https://www.youtube.com/watch?v=N3Yo43uZotE",
      type: "learning-video",
      mediaType: "video",
      duration: "4:21",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "How to Orchestrate Multiple GitHub Copilot Agents (Subagent Tutorial)",
      url: "https://www.youtube.com/watch?v=ALXRvWs4wTg",
      type: "learning-video",
      mediaType: "video",
      duration: "11:20",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "agent-context-handoffs": [
    {
      title: "Understanding multi-agent handoffs",
      url: "https://www.youtube.com/watch?v=WTr6mHTw5cM",
      type: "learning-video",
      mediaType: "video",
      duration: "11:28",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "/handoff is my new favourite skill",
      url: "https://www.youtube.com/watch?v=dtAJ2dOd3ko",
      type: "learning-video",
      mediaType: "video",
      duration: "12:24",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "A2A Protocol (Agent2Agent) Explained: How AI Agents Collaborate",
      url: "https://www.youtube.com/watch?v=Tud9HLTk8hg",
      type: "learning-video",
      mediaType: "video",
      duration: "8:52",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "agent-tool-and-mcp-permissions": [
    {
      title:
        "MCP Security: Sicherheitsrisiken beim Model Context Protocol | Security Podcast",
      url: "https://www.youtube.com/watch?v=n9OiWOeyU-E&t=600s",
      type: "learning-video",
      mediaType: "video",
      duration: "96:14",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
      learningSegment: {
        start: "10:00",
        end: "52:36",
      },
    },
    {
      title: "Why Your MCP Client Needs a Sandbox",
      url: "https://www.youtube.com/watch?v=pGce9T4E5Yw",
      type: "learning-video",
      mediaType: "video",
      duration: "13:08",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "What is Agentic Security Runtime? Securing AI Agents",
      url: "https://www.youtube.com/watch?v=NH0plIdqDMk",
      type: "learning-video",
      mediaType: "video",
      duration: "4:59",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "AI Privilege Escalation: Agentic Identity & Prompt Injection Risks",
      url: "https://www.youtube.com/watch?v=xHJ0_Vm7lK8",
      type: "learning-video",
      mediaType: "video",
      duration: "14:35",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "module-boundaries-and-public-interfaces": [
    {
      title: "Das Java-Modulsystem in der Praxis | Serban Iordache",
      url: "https://www.youtube.com/watch?v=6PuLzd5rvAc",
      type: "learning-video",
      mediaType: "video",
      duration: "59:50",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Introduction to Java Modules | Java for Beginners",
      url: "https://www.youtube.com/watch?v=3KP5YiKLkeo",
      type: "learning-video",
      mediaType: "video",
      duration: "12:42",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Modules in One Lesson",
      url: "https://www.youtube.com/watch?v=MGX-JfMl9-Y",
      type: "learning-video",
      mediaType: "video",
      duration: "45:26",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "How to create Modules in Java 9 - Tutorial",
      url: "https://www.youtube.com/watch?v=89tplxrXJTU",
      type: "learning-video",
      mediaType: "video",
      duration: "9:32",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "tdd-for-domain-behavior": [
    {
      title: "Test-Driven Development (TDD) // deutsch",
      url: "https://www.youtube.com/watch?v=71nLhdZuMk0",
      type: "learning-video",
      mediaType: "video",
      duration: "6:26",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "JUnit 5 Basics 12 - Test driven development with JUnit",
      url: "https://www.youtube.com/watch?v=zFJdQYn9u_8",
      type: "learning-video",
      mediaType: "video",
      duration: "6:18",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Test-Driven Development (TDD) in Java #1 - The 3 Steps of TDD",
      url: "https://www.youtube.com/watch?v=eMU_hninZAs",
      type: "learning-video",
      mediaType: "video",
      duration: "23:25",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Test-Driven Development in Java: Complete Beginner Tutorial (TDD Explained with Real Example)",
      url: "https://www.youtube.com/watch?v=ZEpIYARW6Us",
      type: "learning-video",
      mediaType: "video",
      duration: "9:47",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "archunit-for-java-architecture": [
    {
      title: "ArchUnit: Software-Architektur bewahren von Johannes Thorn",
      url: "https://www.youtube.com/watch?v=hcT2yZRxRvg",
      type: "learning-video",
      mediaType: "video",
      duration: "47:23",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Java ArchUnit Test your Java architecture",
      url: "https://www.youtube.com/watch?v=FAykZTP4Aa4",
      type: "learning-video",
      mediaType: "video",
      duration: "15:16",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Unit Test Your Java Architecture With ArchUnit by Roland Weisleder",
      url: "https://www.youtube.com/watch?v=ef0lUToWxI8",
      type: "learning-video",
      mediaType: "video",
      duration: "43:07",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Unit Test Your Spring Architecture With ArchUnit by Roland Weisleder @ Spring I/O 2024",
      url: "https://www.youtube.com/watch?v=sGmhaizFcEA",
      type: "learning-video",
      mediaType: "video",
      duration: "45:31",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "deterministic-agent-verification-gates": [
    {
      title: "Prozesse mit GitHub Actions // deutsch",
      url: "https://www.youtube.com/watch?v=DAVJ1OGNi4o",
      type: "learning-video",
      mediaType: "video",
      duration: "8:31",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "setting up required github PR checks (beginner - intermediate) anthony explains #315",
      url: "https://www.youtube.com/watch?v=LGY1jPUso5I",
      type: "learning-video",
      mediaType: "video",
      duration: "6:08",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "GitHub Actions Tutorial | Run Automated Tests",
      url: "https://www.youtube.com/watch?v=uFcXrWT4f80",
      type: "learning-video",
      mediaType: "video",
      duration: "4:18",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "How to use GitHub Actions | GitHub for Beginners",
      url: "https://www.youtube.com/watch?v=BQrohJ3PT7I",
      type: "learning-video",
      mediaType: "video",
      duration: "8:04",
      origin: "primary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "automation-value-and-gates": [
    {
      title: "Human in the Loop in n8n (Tutorial, Deutsch)",
      url: "https://www.youtube.com/watch?v=UFCKZ6RjUv4",
      type: "learning-video",
      mediaType: "video",
      duration: "13:41",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Why AI Agents Need A Human in the Loop Now",
      url: "https://www.youtube.com/watch?v=cmEJ-5zYKHA",
      type: "learning-video",
      mediaType: "video",
      duration: "7:27",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "What is Human In The Loop with AI? How HITL Shapes AI Systems",
      url: "https://www.youtube.com/watch?v=9iS-YYLIXiw",
      type: "learning-video",
      mediaType: "video",
      duration: "10:44",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Building AI Agents for Real-World Problems & Workflows",
      url: "https://www.youtube.com/watch?v=4Vg2aVtrX8k",
      type: "learning-video",
      mediaType: "video",
      duration: "7:53",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "java-spring-migrations-with-openrewrite": [
    {
      title:
        "Upgrading your Java & Spring Boot applications with OpenRewrite in IntelliJ",
      url: "https://www.youtube.com/watch?v=e4R6AZHpAD8",
      type: "learning-video",
      mediaType: "video",
      duration: "13:52",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Migrate to Java 25 using OpenRewrite",
      url: "https://www.youtube.com/watch?v=6LGL64AwEEY",
      type: "learning-video",
      mediaType: "video",
      duration: "4:41",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Automate Spring Boot 2.x to 3.x Migration With OpenRewrite  | @Javatechie",
      url: "https://www.youtube.com/watch?v=50mhP1SBTis",
      type: "learning-video",
      mediaType: "video",
      duration: "21:34",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "playwright-for-web-flows": [
    {
      title: "Webseiten testen mit Playwright - German Perl/Raku Workshop 2023",
      url: "https://www.youtube.com/watch?v=-4FpUpePvFM",
      type: "learning-video",
      mediaType: "video",
      duration: "14:35",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Playwright Assertions: Avoid Race Conditions with This Simple Fix!",
      url: "https://www.youtube.com/watch?v=1VxkHP8vfGg",
      type: "learning-video",
      mediaType: "video",
      duration: "1:27",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Playwright Beginner Tutorial 9 | Assertions",
      url: "https://www.youtube.com/watch?v=hYNOFle3zic",
      type: "learning-video",
      mediaType: "video",
      duration: "29:49",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Playwright Assertions: Locator assertions vs Generic assertions explained.",
      url: "https://www.youtube.com/watch?v=e11z1kyLzDM",
      type: "learning-video",
      mediaType: "video",
      duration: "11:11",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "web-xss-and-safe-dom": [
    {
      title: "Schwachstellen einfach erklärt: Cross-Site-Scripting (XSS)",
      url: "https://www.youtube.com/watch?v=Pve8B9RDa1o",
      type: "learning-video",
      mediaType: "video",
      duration: "4:36",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "XSS einfach erklärt – Einführung in Cross-Site Scripting (Reflect, Stored & DOM XSS)",
      url: "https://www.youtube.com/watch?v=ORggQtJBw8w",
      type: "learning-video",
      mediaType: "video",
      duration: "23:25",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "DOM-Based Cross-Site Scripting (DOM XSS) Explained",
      url: "https://www.youtube.com/watch?v=_3Wgx1FabIo",
      type: "learning-video",
      mediaType: "video",
      duration: "7:49",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "OWASP BeNeLux Day Don't trust the DOM: Bypassing XSS mitigations via script gadgets by S. Lekies",
      url: "https://www.youtube.com/watch?v=rssg--FP1AE",
      type: "learning-video",
      mediaType: "video",
      duration: "42:14",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "web-security-baseline": [
    {
      title:
        "OWASP Top 10 2025: Das sind die aktuellen Sicherheitsrisiken | Interview mit Christian Wenz",
      url: "https://www.youtube.com/watch?v=R1KSXSd_lmk",
      type: "learning-video",
      mediaType: "video",
      duration: "16:51",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "OWASP Top 10 2025 explained:  What it is, what changed, and how to use it",
      url: "https://www.youtube.com/watch?v=qzvfKXynk-I",
      type: "learning-video",
      mediaType: "video",
      duration: "6:50",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Top 10 Security Risks in AI Agents Explained",
      url: "https://www.youtube.com/watch?v=soFWS8NBcSU",
      type: "learning-video",
      mediaType: "video",
      duration: "8:58",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Securing AI Agents: How to Prevent Hidden Prompt Injection Attacks",
      url: "https://www.youtube.com/watch?v=5ZA1lTxTH3c",
      type: "learning-video",
      mediaType: "video",
      duration: "10:07",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "ui-design-system-workflow": [
    {
      title: "Storybook Crashkurs - Komponentenbasierte UI Entwicklung",
      url: "https://www.youtube.com/watch?v=UPrnl4gBmhc",
      type: "learning-video",
      mediaType: "video",
      duration: "26:22",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Intro to Design Systems | Penpot Hands-On Demo",
      url: "https://www.youtube.com/watch?v=kyu2L-4zeWg&t=152s",
      type: "learning-video",
      mediaType: "video",
      duration: "58:43",
      origin: "primary",
      language: "en",
      checkedAt: "2026-09-30",
      learningSegment: {
        start: "02:32",
        end: "43:22",
      },
    },
    {
      title: "Component testing in Storybook with play functions",
      url: "https://www.youtube.com/watch?v=dcuzwCHI940",
      type: "learning-video",
      mediaType: "video",
      duration: "6:56",
      origin: "primary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Accessibility Testing in Storybook with Axe and Playwright",
      url: "https://www.youtube.com/watch?v=63nQ9qC3Tck",
      type: "learning-video",
      mediaType: "video",
      duration: "7:59",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "technical-documentation-generation": [
    {
      title: "Javadoc - Dokumentationskommentare",
      url: "https://www.youtube.com/watch?v=heIVLnVXfmk",
      type: "learning-video",
      mediaType: "video",
      duration: "13:02",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Java-Dokumentationen erzeugen | Einstieg in Java",
      url: "https://www.youtube.com/watch?v=pWfffdV0VUY",
      type: "learning-video",
      mediaType: "video",
      duration: "7:05",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "JavaDoc Hits the Markdown on Comments - Inside Java Newscast #68",
      url: "https://www.youtube.com/watch?v=AvAIFq4fLPw",
      type: "learning-video",
      mediaType: "video",
      duration: "6:53",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "JEP Explained. JEP 467: Markdown Documentation Comments",
      url: "https://www.youtube.com/watch?v=hEWU2OMtNnw",
      type: "learning-video",
      mediaType: "video",
      duration: "44:58",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "dependency-security-assessment": [
    {
      title: "Supply Chain Security Explained - deutsch - 4k - 8k",
      url: "https://www.youtube.com/watch?v=2cEKEEJraDk",
      type: "learning-video",
      mediaType: "video",
      duration: "31:18",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Preventing Software Supply Chain Attacks With Dependency Management Best Practices",
      url: "https://www.youtube.com/watch?v=7IoXciSucw4",
      type: "learning-video",
      mediaType: "video",
      duration: "15:00",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Software supply chain and vulnerability assessment with syft and grype",
      url: "https://www.youtube.com/watch?v=ee-jtLAmGnI",
      type: "learning-video",
      mediaType: "video",
      duration: "7:18",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Supply Chain Vulnerabilities - CompTIA Security+ SY0-701 - 2.3",
      url: "https://www.youtube.com/watch?v=WqvCJLpwExY",
      type: "learning-video",
      mediaType: "video",
      duration: "9:12",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "review-and-accept-ai-generated-changes": [
    {
      title: "Code-Reviews // deutsch",
      url: "https://www.youtube.com/watch?v=b35FvjoUqUs",
      type: "learning-video",
      mediaType: "video",
      duration: "4:34",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "How I Review AI-Generated Code",
      url: "https://www.youtube.com/watch?v=As2xy_cSx00",
      type: "learning-video",
      mediaType: "video",
      duration: "14:20",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "How Developers Secure AI-Generated Code: 5 Security Best Practices",
      url: "https://www.youtube.com/watch?v=X0UI0O8YzJM",
      type: "learning-video",
      mediaType: "video",
      duration: "11:27",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "How AI Is Changing Code Reviews & Software Development",
      url: "https://www.youtube.com/watch?v=c57vAe-mMLo",
      type: "learning-video",
      mediaType: "video",
      duration: "14:09",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "compare-parallel-and-serial-agent-work": [
    {
      title:
        "Single Agent Vs. Multi-Agent Systems in AI | How To Choose The Right Architecture",
      url: "https://www.youtube.com/watch?v=2lTFI6FAqhk",
      type: "learning-video",
      mediaType: "video",
      duration: "3:44",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Observability and Evals for AI Agents: A Simple Breakdown",
      url: "https://www.youtube.com/watch?v=FDVdLrloFOw",
      type: "learning-video",
      mediaType: "video",
      duration: "14:44",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Evaluating and Debugging Non-Deterministic AI Agents",
      url: "https://www.youtube.com/watch?v=4u64WEuQHYE",
      type: "learning-video",
      mediaType: "video",
      duration: "7:14",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "bug-triage-and-pr-automation": [
    {
      title: "How the GitHub Copilot coding agent works | GitHub Checkout",
      url: "https://www.youtube.com/watch?v=1GVBRhDI5No",
      type: "learning-video",
      mediaType: "video",
      duration: "6:58",
      origin: "primary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Use GitHub Copilot Coding Agent to solve open issues in a GitHub repository",
      url: "https://www.youtube.com/watch?v=sMVESy4jHLg",
      type: "learning-video",
      mediaType: "video",
      duration: "12:59",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Jira Ticket ➡️ GitHub Pull Request (Automatically!) with Custom Copilot Agents and Agentic Workflows",
      url: "https://www.youtube.com/watch?v=kaIz0X_YByE",
      type: "learning-video",
      mediaType: "video",
      duration: "24:54",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "local-model-stack-evaluation": [
    {
      title: "Was ich über lokale KI gelernt habe",
      url: "https://www.youtube.com/watch?v=M1j_uRqKMKI",
      type: "learning-video",
      mediaType: "video",
      duration: "22:28",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Lokale KI in VS Code: Ollama Guide & Modellwahl",
      url: "https://www.youtube.com/watch?v=i96JY0zzEZg",
      type: "learning-video",
      mediaType: "video",
      duration: "10:38",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Learn Ollama in 15 Minutes - Run LLM Models Locally for FREE",
      url: "https://www.youtube.com/watch?v=UtSSMs6ObqY",
      type: "learning-video",
      mediaType: "video",
      duration: "14:01",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "How to Run a Local AI Agent with Ollama, Qwen 3, and LangGraph",
      url: "https://www.youtube.com/watch?v=MAZUI4jGlU8",
      type: "learning-video",
      mediaType: "video",
      duration: "12:48",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "coding-harness-design": [
    {
      title: "Das Geheimnis guter KI-Agents: Die Harness-Schicht erklärt",
      url: "https://www.youtube.com/watch?v=7_F2rGhK0iE",
      type: "learning-video",
      mediaType: "video",
      duration: "9:47",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Harness Engineering Explained in 22 Minutes",
      url: "https://www.youtube.com/watch?v=UmZytjgs2eo",
      type: "learning-video",
      mediaType: "video",
      duration: "22:39",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title:
        "Harness Engineering: Building the Production Cage for Powerful Domain Agents — Mike Chambers, AWS",
      url: "https://www.youtube.com/watch?v=gxVZ_1tuuq4",
      type: "learning-video",
      mediaType: "video",
      duration: "20:46",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Why Your MCP Client Needs a Sandbox",
      url: "https://www.youtube.com/watch?v=pGce9T4E5Yw",
      type: "learning-video",
      mediaType: "video",
      duration: "13:08",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
  "focused-git-commits": [
    {
      title: "Git add - Die staging area sinnvoll nutzen",
      url: "https://www.youtube.com/watch?v=Tl9PV3Kso_k",
      type: "learning-video",
      mediaType: "video",
      duration: "5:14",
      origin: "secondary",
      language: "de",
      checkedAt: "2026-09-30",
    },
    {
      title: "Git Interactive staging",
      url: "https://www.youtube.com/watch?v=zzh7cRpTNS4",
      type: "learning-video",
      mediaType: "video",
      duration: "6:18",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Atomic Commits Explained: Stop Writing Useless Git Messages",
      url: "https://www.youtube.com/watch?v=zH0mn7gktsQ",
      type: "learning-video",
      mediaType: "video",
      duration: "6:28",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
    {
      title: "Git Basics Atomic Commits",
      url: "https://www.youtube.com/watch?v=16xT6BYoVr4",
      type: "learning-video",
      mediaType: "video",
      duration: "2:32",
      origin: "secondary",
      language: "en",
      checkedAt: "2026-09-30",
    },
  ],
};
