export const congratulations = [
  "Herzlichen Glückwunsch!",
  "Glückwunsch, das war stark!",
  "Bravo, alles richtig!",
  "Großartig gemacht!",
  "Fünf Richtige – wunderbar!",
  "Ein glänzender Abschluss!",
  "Geschafft – mit Bravour!",
  "Punktlandung!",
  "Das war überzeugend!",
  "Ein Ergebnis zum Freuen!",
  "Hervorragend!",
  "Tolle Leistung!",
  "Das kann sich sehen lassen!",
  "Fünf Fragen, fünf Treffer!",
  "Souverän gelöst!",
  "Alles richtig – wie schön!",
  "Volltreffer auf ganzer Linie!",
  "Fünfmal richtig – Chapeau!",
  "Ein rundum gelungener Durchlauf!",
  "Das sitzt!",
  "Ein guter Blick fürs Wesentliche!",
  "Klar gedacht, richtig entschieden.",
  "Fünf gute Entscheidungen hintereinander!",
  "Ein feiner Moment zum Feiern!",
  "Starke Entscheidungen, schöner Abschluss!",
  "Das verdient ein Lächeln.",
  "Eine Runde Applaus für diesen Durchlauf!",
  "Hier passt einfach alles.",
  "Ein Ergebnis wie aus einem Guss.",
  "Beste Mischung: Neugier und Klarheit.",
  "Ein starker Schlusspunkt!",
  "Das war ein guter Lauf!",
  "Fünfmal auf den Punkt.",
  "Ein Grund, kurz stolz zu sein.",
  "Wissen, das im richtigen Moment da ist.",
  "Das war aufmerksam und treffsicher!",
  "Ein kleiner Triumph zum Mitnehmen.",
  "So macht Lernen Freude!",
  "Ein schönes Stück Klarheit gewonnen.",
  "Die Antworten sitzen, der Moment gehört gefeiert!",
  "Künstliche Intelligenz? Hier glänzt die natürliche!",
  "Fünf Treffer – ein ziemlich guter Output!",
  "Der Prompt: nachdenken. Der Output: fünf Richtige.",
  "Kontext verstanden, Antworten getroffen!",
  "Keine Halluzination: Dieses Ergebnis ist echt.",
  "Mensch im Loop, Freude im Blick!",
  "Bestes Modell für heute: neugierig bleiben.",
  "Vom Input zum Aha – fünfmal geglückt!",
  "Ergebnis geprüft: Anlass zur Freude gefunden.",
  "KI kann unterstützen. Dieser Erfolg gehört dem Menschen.",
] as const;
